server:
  port: 8082

spring:
  application:
    name: account-service

  datasource:
    url: jdbc:postgresql://localhost:5433/fintrack_accounts
    username: fintrack
    password: fintrack123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

jwt:
  secret: "fintrack-super-secret-key-must-be-at-least-256-bits-long-for-hs256-algorithm"
  expiration: 900000

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.fintrack: DEBUG
    org.springframework.kafka: INFO